name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
filter-by-commitish: true
commitish: prod-*

template: |
  ## Changes
  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'