on: pull_request_review
name: Label approved pull requests
jobs:
  labelWhenApproved:
    if: ${{ github.event.label.name != 'Do Not Merge' }}
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Mergeable"
        REMOVE_LABEL: "%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E6%B1%82%E3%82%80"