name: Release Drafter

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get latest release
        run: |
          echo 'RELEASE<<EOF' >> $GITHUB_ENV
          echo $(curl -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - run: |
          echo "${{ fromJSON(env.RELEASE).tag_name }}" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
      - name: release publish
        run: |
          echo 'PUBLISH_RELEASE<<EOF' >> $GITHUB_ENV
          echo $(curl -X PATCH -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/${{ fromJSON(env.RELEASE).id }} -d '{"draft":"false"}' | jq -r .) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV