name: Release Drafter

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate CalVer version
        id: calver
        run: |
          export VERSION=prod-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M)
          echo "::set-output name=tag_name::$VERSION"
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ steps.calver.outputs.tag_name }}
          tag: ${{ steps.calver.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}