name: Release Drafter

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate CalVer version
        id: calver
        run: |
          export VERSION=stg-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M)
          echo "::set-output name=tag_name::$VERSION"
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ steps.calver.outputs.tag_name }}
          tag: ${{ steps.calver.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get latest release
        run: |
          echo 'RELEASE<<EOF' >> $GITHUB_ENV
          echo $(curl -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - id: get_release_note
        name: get release note
        run: |
          # 改行コードをエスケープする
          release_body='${{ steps.create_release.outputs.body }}'
          release_body=${release_body//$'\r\n'/\\n}
          release_body=${release_body//$'\n'/\\n}
          echo "::set-output name=body::$release_body"
      - name: notify to Slack
        id: slack
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: A release is published.
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "リリースノートが作成されました(${{ steps.create_release.outputs.tag_name }})"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Author:*\n${{ github.actor }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*リリース内容:*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.get_release_note.outputs.body }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                    "type": "plain_text",
                    "text": "リリースノート詳細",
                    "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ steps.create_release.outputs.html_url }}"
                  },
                ]
              }
            ]