name: Required Pull Request Labels

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled, unlabeled, review_requested, ready_for_review]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "bugfix, feature, improvements"
          add_comment: true
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 0
          labels: "Do Not Merge"
          add_comment: true